language: php

php:
  -7.2

services: mysql
before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS kopiqu;'
  -  mysql -e 'USE kopiqu;create table users(id int,email varchar(256),role varchar(256));'
  -  mysql -e "USE kopiqu; insert into users values ('1' , 'testemail@test.com' , 'admin1');"
  - composer self update
  - composer install --no-interaction


script:
  - vendor/bin/phpunit
